# Generated by Django 3.2.9 on 2022-02-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tagline',
        ),
        migrations.AddField(
            model_name='posts',
            name='tagline',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rww', to=settings.AUTH_USER_MODEL),
        ),
    ]
